from enum import Enum


class InputType(str, Enum):
    EXCEL = "EXCEL"
    IMAGE = "IMAGE"


class TaskStatus(str, Enum):
    CREATED = "CREATED"
    PARSING_INPUT = "PARSING_INPUT"
    INPUT_PARSED = "INPUT_PARSED"
    TEMPLATE_RETRIEVED = "TEMPLATE_RETRIEVED"
    RULE_RETRIEVED = "RULE_RETRIEVED"
    RULE_DRAFTED = "RULE_DRAFTED"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    READY_TO_RUN = "READY_TO_RUN"
    TRANSFORMING = "TRANSFORMING"
    PREVIEW_READY = "PREVIEW_READY"
    FINAL_CONFIRMED = "FINAL_CONFIRMED"
    EXPORTED = "EXPORTED"
    FAILED = "FAILED"
    NEED_SOURCE_FIX = "NEED_SOURCE_FIX"


class PreviewValidationStatus(str, Enum):
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    ERROR = "ERROR"
